### ISSUE TITLE
error in getQuickstat()

### ISSUE THREAD

**Issue by kotamine** [bradlindblad/tidyUSDA#18]
Hi I am using exactly the same code you posted but I get the following error message; 

Error in st_as_sfc.SpatialPolygons(sp::geometry(x), ...) : 
  package rgeos required for finding out which hole belongs to which exterior ring

**Comment by lindblb** [comment]
Which OS? Any any other system info please.

**Comment by kotamine** [comment]
thanks I am using Mac OS 10.14.6

**Comment by kotamine** [comment]
is there any relationship to the package tidycensus?   just curious

**Comment by lindblb** [comment]
Can you try installing rgeos like it suggests.

`install.packages("rgeos")`

**Comment by kotamine** [comment]
Hi thanks! After installing rgeos, getQuickstat() works now. 
However, plotUSDA() does not work for me. It freezes R.  I don't know why that happens and I have a similar issue with tidycensus' map function in some cases.

**Comment by bradlindblad** [comment]
Please see [issue #15 ](https://github.com/bradlindblad/tidyUSDA/issues/15). This is a known limitation of the default graphics device on Mac, otherwise discussed in the documentation. I recommend taking the output from getQuickstat() and plotting with tmap or leaflet packages if you are on Mac.
