### ISSUE TITLE
Returns sf errors

### ISSUE THREAD

**Issue by chriszs** [bradlindblad/tidyUSDA#40]
When running `getQuickstat` I was getting errors at [this line](https://github.com/bradlindblad/tidyUSDA/blob/85670bc6fc2269e809bbb4287cd6f779ad9bc2c6/R/getQuickstat.R#L440) that said `trying to get slot "data" from an object (class "sf") that is not an S4 object`. I tried the example on the package README and got the same error. Turns out the tigris package just released a new 1.0 that switches to sf frames for geography. I solved this by manually downgrading tigris to the release before 1.0.

**Comment by bradlindblad** [comment]
Thanks for this, fixed in version 0.2.9 https://github.com/bradlindblad/tidyUSDA/releases/tag/v0.2.9
