### ISSUE TITLE
How to pull data from the USDA's WASDE in the tidyUSDA package?

### ISSUE THREAD

**Issue by tanga94** [bradlindblad/tidyUSDA#52]
Hi, I would like to find out whether data from the USDA's monthly release of the World Agricultural Supply and Demand Estimates (WASDE) is available in this package? And if yes, do you perhaps have some sample code on how to pull forecasts from this report?

Thanks!

**Comment by bradlindblad** [comment]
No it is not. This package only pulls data available at this location:https://quickstats.nass.usda.gov/
