### ISSUE TITLE
Error in UseMethod("left_join")

### ISSUE THREAD

**Issue by Noe-J-Nava** [bradlindblad/tidyUSDA#55]
`getQuickstat()`, as show below, spits out the following error message. Notice there are two issues with that error. First, it states it is retrieving data for the year of 2020. This is incorrect since I want the data for 2017. Since I am unable to retrieve data, I cannot check if this is just a labelling issue or it is indeed retrieving the wrong data. 

```
Retrieving data for the year 2020
  |======================================================| 100%
Error in UseMethod("left_join") : 
  no applicable method for 'left_join' applied to an object of class "list"
````

The reproduceable example is here:

```
yields <- getQuickstat(
  sector = "CROPS",
  group  = "FIELD CROPS",
  commodity = "CORN",
  category = "YIELD",
  domain = "TOTAL",
  county = NULL,
  key = APIkey,
  program = 'CENSUS',
  data_item = "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",
  geographic_level = "COUNTY",
  year = "2017",
  state = NULL,
  geometry = TRUE,
  lower48 = TRUE, 
  weighted_by_area = TRUE)
```

**Comment by bradlindblad** [comment]
@Noe-J-Nava have you been able to pull this data from the [NASS website](https://quickstats.nass.usda.gov/)? I ask because I can't seem to find this combination of input params. 

The closest data item I could find was `CORN, GRAIN, NON-IRRIGATED - YIELD, MEASURED IN BU / ACRE`

**Comment by bradlindblad** [comment]
@Noe-J-Nava this is the closest set of params to your request above that I was able to get to work:

```
getQuickstat(
  # sector = "CROPS",
  # group  = "FIELD CROPS",
  # commodity = "CORN",
  # category = "YIELD",
  # domain = "TOTAL",
  # county = NULL,
  key = APIkey,
  program = 'CENSUS',
  data_item = "CORN, GRAIN, NON-IRRIGATED - YIELD, MEASURED IN BU / ACRE",
  geographic_level = "STATE",
  year = "2013",
  state = NULL,
  geometry = TRUE,
  lower48 = TRUE,
  weighted_by_area = TRUE)
```

**Comment by Noe-J-Nava** [comment]
@bradlindblad, I have not tried tidyUSDA:: recently, but I ended up using rnassqs::. I am not sure if the problem persisted for me. I am adding my params employed in the latter package:

```
  params <- list( # Necessary params to narrow down query
    sector_desc       = "CROPS",
    group_desc        = "FIELD CROPS",
    commodity_desc    = "CORN",
    year              = y,
    statisticcat_desc = "YIELD",
    short_desc        = "CORN, GRAIN - YIELD, MEASURED IN BU / ACRE",
    agg_level_desc    = "COUNTY"
  )
  
```

**Comment by bradlindblad** [comment]
I would verify those exact Params from the other package work in NASS. The other package might do any number of things that probably won't transfer over to another package.

**Comment by Noe-J-Nava** [comment]
@bradlindblad, I tested your code on my computer, along with a previous work that it was tested to work. They are working now. I maybe had an issue in y parameters, or there was an issue with API. In any case, it is working now for me.
