### ISSUE TITLE
Error retreiving data from getQuickstat

### ISSUE THREAD

**Issue by leandra6** [bradlindblad/tidyUSDA#59]
I have used the getQuickstat function in USDAtidy previously without errors, but today I keep getting the following error:
 "Error in UseMethod("left_join") : 
  no applicable method for 'left_join' applied to an object of class "list".

any suggestion on how to fix this?

sample code:
agDF1 <- tidyUSDA::getQuickstat(
  sector = NULL,
  group = NULL,
  commodity = NULL,
  category = NULL,
  domain = NULL,
  county = NULL,
  key = key,
  program = 'SURVEY',
  data_item = 'LIVESTOCK TOTALS - PRODUCTION, MEASURED IN LB',
  geographic_level = 'COUNTY',
  year = '2020',
  state = 'OREGON',
  geometry = TRUE,
  lower48 = TRUE)

**Comment by bradlindblad** [comment]
I don't see this as a valid data point in the NASS database:

![image](https://github.com/bradlindblad/tidyUSDA/assets/34219856/c9de82e0-4adc-43a1-8951-bbedcc3b4df4)
